# Generated by Django 5.1.4 on 2024-12-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='balls_bowled',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='team1_runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='team1_wickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_wickets',
            field=models.IntegerField(default=0),
        ),
    ]
