# Generated by Django 5.1.4 on 2024-12-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0002_match_balls_bowled_match_team1_runs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='batting_team',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
