# Generated by Django 5.1.4 on 2024-12-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0003_match_batting_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team1_no_balls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='team1_wides',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_no_balls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_wides',
            field=models.IntegerField(default=0),
        ),
    ]
