# Generated by Django 5.1.4 on 2024-12-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0004_match_team1_no_balls_match_team1_wides_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_free_hit',
            field=models.BooleanField(default=False),
        ),
    ]
