# Generated by Django 5.1.4 on 2024-12-21 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0005_match_is_free_hit'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='current_bowler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_bowler', to='cricket.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='non_striker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='non_striker', to='cricket.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='striker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='striker', to='cricket.player'),
        ),
    ]
