# Generated by Django 5.1.4 on 2024-12-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0006_match_current_bowler_match_non_striker_match_striker'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_out',
            field=models.BooleanField(default=False),
        ),
    ]
