# Generated by Django 5.1.4 on 2024-12-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0007_player_is_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='balls_in_current_over',
            field=models.IntegerField(default=0),
        ),
    ]
