# Generated by Django 5.1.4 on 2024-12-22 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0008_match_balls_in_current_over'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_players', to='cricket.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket.player')),
            ],
        ),
    ]
