# Generated by Django 5.1.4 on 2025-01-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0009_outplayer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='balls_in_current_over',
            new_name='balls_in_over',
        ),
        migrations.AddField(
            model_name='match',
            name='current_over',
            field=models.IntegerField(default=0),
        ),
    ]
