# Generated by Django 5.1.4 on 2025-01-02 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0010_rename_balls_in_current_over_match_balls_in_over_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='balls_in_over',
            new_name='balls_in_current_over',
        ),
        migrations.RemoveField(
            model_name='match',
            name='current_over',
        ),
    ]
