# Generated by Django 5.1.4 on 2025-01-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0012_match_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
