# Generated by Django 5.1.4 on 2025-01-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0013_match_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='name',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team2',
        ),
        migrations.AddField(
            model_name='match',
            name='team1_name',
            field=models.CharField(default='Team 1', max_length=50),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_name',
            field=models.CharField(default='Team 2', max_length=50),
        ),
    ]
