# Generated by Django 4.2.20 on 2025-03-07 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0014_remove_match_name_remove_match_team1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='balls_in_current_over',
        ),
        migrations.AddField(
            model_name='match',
            name='batters',
            field=models.ManyToManyField(blank=True, related_name='batting_matches', to='cricket.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='bowlers',
            field=models.ManyToManyField(blank=True, related_name='bowling_matches', to='cricket.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='previous_bowler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_bowler', to='cricket.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='outplayer',
            name='balls_faced',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='outplayer',
            name='runs_scored',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='balls_faced',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='fours_hit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='overs_bowled',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='runs_given',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='sixes_hit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stat',
            name='balls_faced',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stat',
            name='catches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stat',
            name='fours_hit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stat',
            name='overs_bowled',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stat',
            name='run_outs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stat',
            name='runs_given',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stat',
            name='runs_scored',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stat',
            name='sixes_hit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stat',
            name='wickets_taken',
            field=models.IntegerField(default=0),
        ),
    ]
