# Generated by Django 4.2.20 on 2025-03-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0015_remove_match_balls_in_current_over_match_batters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='balls_in_current_over',
            field=models.IntegerField(default=0),
        ),
    ]
