# Generated by Django 4.2.20 on 2025-04-02 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0016_match_balls_in_current_over'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='balls_in_current_over',
        ),
    ]
